package Source;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import static Source.Login_Page.cryptWithMD5;
import com.formdev.flatlaf.FlatDarkLaf;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;

/**
 *  @author Tanuj & Shravan
\
 */
public class Register_Page extends javax.swing.JFrame {
    static final String DB_URL="jdbc:mysql://localhost:3306/student";
    static final String User="root";
    static final String Pass="";
    private static MessageDigest md;
    /**
     * Creates new form Register
     */
    public Register_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        U_name = new javax.swing.JTextField();
        UEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Upass = new javax.swing.JPasswordField();
        Ucpass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setLocation(new java.awt.Point(760, 240));
        setMaximizedBounds(new java.awt.Rectangle(442, 500, 500, 500));
        setMaximumSize(new java.awt.Dimension(442, 500));
        setMinimumSize(new java.awt.Dimension(442, 500));
        setPreferredSize(new java.awt.Dimension(442, 520));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(43, 45, 45));
        jPanel1.setMaximumSize(new java.awt.Dimension(442, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(442, 500));
        jPanel1.setName("Register"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(442, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create your account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 52, -1, -1));

        U_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(U_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 122, 280, 30));

        UEmail.setBorder(U_name.getBorder());
        jPanel1.add(UEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 280, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel3.setFont(jLabel2.getFont());
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 162, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        Register.setBackground(new java.awt.Color(102, 153, 255));
        Register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Register.setText("Register");
        Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 280, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Already signed up? ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 425, -1, -1));

        Upass.setBorder(U_name.getBorder());
        jPanel1.add(Upass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 280, 30));

        Ucpass.setBorder(U_name.getBorder());
        jPanel1.add(Ucpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 280, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login now!");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("NEW ACCOUNT?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 443, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        Connection con;
        PreparedStatement ps;
        // Textbox inputs transferred to variables
        String Email = UEmail.getText();
        String name = U_name.getText();
        String password = Upass.getText();
        String cpassword = Ucpass.getText();
        // Checks if all the fields are entered
        if(name.equals("") || password.equals("") || cpassword.equals("")){
            JOptionPane.showMessageDialog(null,"Some informations are missing","Error",JOptionPane.ERROR_MESSAGE);  
        }    
        else{   
            if(!isValid(Email)){
                JOptionPane.showMessageDialog(null,"Invalid E-Mail","Error",JOptionPane.ERROR_MESSAGE);  
            }
            else if(password.equals(cpassword)){ //Checks if password and confirm password are same
                       try{
                           String SB = cryptWithMD5(password);
                        con = DriverManager.getConnection(DB_URL,User,Pass);
                        //insert into login table
                        ps = con.prepareStatement("insert into login(Uname,Upassword, Email) " + "values (?,?,?)");
                        ps.setString(1,name); //Namae
                        ps.setString(2,SB); //Password
                        ps.setString(3,Email); //Email
                        ps.executeUpdate(); // Update the table
                        JOptionPane.showMessageDialog(null,"Registered Successfully");
                        dispose();
                    }
                 catch(SQLException se){
                        se.printStackTrace(); // throw an exception
                    }
                System.out.printf("Register Succesffull");  // Console : Register Successfull
                   new Login_Page().setVisible(true);
               }
               else{
                   JOptionPane.showMessageDialog(null,"Password and Confirm Password don't match","Error",JOptionPane.ERROR_MESSAGE); // Error dialogue box
               }
               
        }
    }//GEN-LAST:event_RegisterActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new Login_Page().setVisible(true); //Opens Login Window
        this.dispose(); // Closes the register window
    }//GEN-LAST:event_jLabel7MouseClicked

    public static String cryptWithMD5(String pass){
    try {
        md = MessageDigest.getInstance("MD5");
        byte[] passBytes = pass.getBytes();
        md.reset();
        byte[] digested = md.digest(passBytes);
        StringBuffer sb = new StringBuffer();
        for(int i=0;i<digested.length;i++){
            sb.append(Integer.toHexString(0xff & digested[i]));
        }
        return sb.toString();
    } catch (NoSuchAlgorithmException ex) {
        Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
    }
        return null;
   }
    
    public static boolean isValid(String email){  
        String emailFormate ="^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+(?:\\."  
                + "[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$";  
          
        Pattern p = Pattern.compile(emailFormate);  
        if(email == null){  
        return false;  
        }   
        return p.matcher(email).matches();  
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                new Register_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register;
    private javax.swing.JTextField UEmail;
    private javax.swing.JTextField U_name;
    private javax.swing.JPasswordField Ucpass;
    private javax.swing.JPasswordField Upass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


}
