/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Source;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.JOptionPane;

/**
 *
 * @author Tanuj & Shravan
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoadingText = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        Valuee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadingText.setForeground(new java.awt.Color(255, 255, 255));
        LoadingText.setText("Loading Modules..");
        jPanel1.add(LoadingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, -1));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/logo.png"))); // NOI18N
        jPanel1.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 0, 618, -1));

        jProgressBar1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jProgressBar1StateChanged(evt);
            }
        });
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 490, 920, 10));

        Valuee.setText("jLabel2");
        jPanel1.add(Valuee, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jProgressBar1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jProgressBar1StateChanged
        if(jProgressBar1.getPercentComplete()== 1.0){
            this.dispose();
            new Login_Page().setVisible(true);
        }
    }//GEN-LAST:event_jProgressBar1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();

        /* Create and display the form */
       SplashScreen sp = new SplashScreen();
       sp.setVisible(true);
       try {
           for(int i=0; i<=100;i++ ){
               Thread.sleep(100);
               
               sp.Valuee.setText(i + "%");
               
               if(i==10){
                   sp.LoadingText.setText("Loading Modules");
               }
               if(i==20){
                   sp.LoadingText.setText("Connecting Database");
             
               }
               if(i==50){
                   sp.LoadingText.setText("Building GUI");
               }
               if(i==90){
                   sp.LoadingText.setText("Launching Application");
               }
               sp.jProgressBar1.setValue(i);
               
           }
       }catch (InterruptedException e){
           JOptionPane.showMessageDialog(null ,e);
       }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel LoadingText;
    private javax.swing.JLabel Valuee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
