package Source;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tanuj & Shravan
 */
public class Window extends javax.swing.JFrame {

              static final String DB_URL = "jdbc:mysql://localhost:3306/student"; //Database URL
        static final String User = "root"; //Database Username
        static final String Pass = "";  //Database Password
        DefaultTableModel dm;
        Connection con;
        Calendar c = Calendar.getInstance();
        int timeOfDay = c.get(Calendar.HOUR_OF_DAY);
        PreparedStatement ps;
        String File_Name = "";
        byte[] P_Image = null;
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        if(timeOfDay >= 0 && timeOfDay < 12){
            Time.setText("Good Morning");     
        }else if(timeOfDay >= 12 && timeOfDay < 16){
            Time.setText("Good Afternoon");   
        }else if(timeOfDay >= 16 && timeOfDay < 21){
            Time.setText("Good Evening");
        }else if(timeOfDay >= 21 && timeOfDay < 24){
            Time.setText("Good Night");
        }
            Students.setVisible(false);
            Fees.setVisible(false);
            ID.setVisible(false);
            Home.setVisible(true);
            Delete_B.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        SideBar = new javax.swing.JPanel();
        Logout_opt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Home_opt = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Student_opt = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ID_opt = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Fees_opt = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Main_panel = new javax.swing.JPanel();
        ID = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        IdentityCard = new javax.swing.JPanel();
        Profile_Image = new javax.swing.JLabel();
        Blood1 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        Birthdate1 = new javax.swing.JLabel();
        Phone1 = new javax.swing.JLabel();
        Class1 = new javax.swing.JLabel();
        IDImage = new javax.swing.JLabel();
        Class = new javax.swing.JComboBox<>();
        Student = new javax.swing.JComboBox<>();
        Choose = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Students = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Stud_table = new javax.swing.JTable();
        class_list = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Grid_search = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Delete_B = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        Home = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        Time = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Fees = new javax.swing.JPanel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informix School Management System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(900, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideBar.setBackground(new java.awt.Color(33, 33, 33));
        SideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout_opt.setBackground(new java.awt.Color(153, 153, 0));
        Logout_opt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout_opt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_optMouseClicked(evt);
            }
        });
        Logout_opt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/Logout_35px.png"))); // NOI18N
        Logout_opt.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, 40, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logout");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logout_opt.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 12, -1, -1));

        SideBar.add(Logout_opt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 200, 50));

        Home_opt.setBackground(new java.awt.Color(66, 66, 66));
        Home_opt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home_opt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_optMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Home_optMouseEntered(evt);
            }
        });
        Home_opt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/home_50px.png"))); // NOI18N
        Home_opt.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, 40, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Home");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home_opt.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 12, -1, -1));

        SideBar.add(Home_opt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 50));

        Student_opt.setBackground(new java.awt.Color(33, 33, 33));
        Student_opt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Student_opt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Student_optMouseClicked(evt);
            }
        });
        Student_opt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/identification_documents_40px.png"))); // NOI18N
        Student_opt.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, 40, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Students");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Student_opt.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 12, -1, -1));
        jLabel6.getAccessibleContext().setAccessibleName("75");

        SideBar.add(Student_opt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 50));

        ID_opt.setBackground(new java.awt.Color(33, 33, 33));
        ID_opt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ID_opt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ID_optMouseClicked(evt);
            }
        });
        ID_opt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ID_optKeyPressed(evt);
            }
        });
        ID_opt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/name_tag_50px.png"))); // NOI18N
        ID_opt.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 50, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Card");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ID_opt.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 12, -1, -1));

        SideBar.add(ID_opt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 50));

        Fees_opt.setBackground(new java.awt.Color(33, 33, 33));
        Fees_opt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fees_opt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fees_optMouseClicked(evt);
            }
        });
        Fees_opt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Fees_optKeyPressed(evt);
            }
        });
        Fees_opt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/bill_50px.png"))); // NOI18N
        Fees_opt.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 50, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Fees");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Fees_opt.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 12, -1, -1));

        SideBar.add(Fees_opt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/logo-removebg-preview (1).jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        SideBar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 150));

        getContentPane().add(SideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        Main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setBackground(new java.awt.Color(23, 23, 23));
        ID.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Select the Student");
        ID.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        ID.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 680, 10));

        jPanel2.setBackground(new java.awt.Color(215, 35, 35));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Identity Card");
        jPanel2.add(jLabel9);

        ID.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IdentityCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        IdentityCard.add(Profile_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 76, 160, 160));

        Blood1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        Blood1.setForeground(new java.awt.Color(51, 51, 51));
        Blood1.setText("Blood ");
        IdentityCard.add(Blood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        Name1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        Name1.setForeground(new java.awt.Color(51, 51, 51));
        Name1.setText("Name ");
        IdentityCard.add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 153, -1, -1));

        Birthdate1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        Birthdate1.setForeground(new java.awt.Color(51, 51, 51));
        Birthdate1.setText("Date ");
        IdentityCard.add(Birthdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 195, -1, -1));

        Phone1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        Phone1.setForeground(new java.awt.Color(51, 51, 51));
        Phone1.setText("Number ");
        IdentityCard.add(Phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        Class1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        Class1.setForeground(new java.awt.Color(51, 51, 51));
        Class1.setText("Class ");
        IdentityCard.add(Class1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 70, -1));

        IDImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/Identity-Card.png"))); // NOI18N
        IdentityCard.add(IDImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.add(IdentityCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 592, 340));

        ID.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 700, 400));

        Class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Class", "Class 8", "Class 9", "Class 10" }));
        Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassActionPerformed(evt);
            }
        });
        ID.add(Class, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        Student.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student" }));
        Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentActionPerformed(evt);
            }
        });
        ID.add(Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, -1));

        Choose.setText("Choose");
        Choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseActionPerformed(evt);
            }
        });
        ID.add(Choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        ID.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        jLabel13.setText("Class :");
        ID.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, -1, -1));

        jLabel22.setText("Student :");
        ID.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 103, -1, -1));

        jLabel23.setText("Student's Photo :");
        ID.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 103, -1, -1));

        jLabel24.setText("Print ID Card :");
        ID.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 103, -1, -1));

        Main_panel.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        Students.setBackground(new java.awt.Color(204, 204, 204));
        Students.setForeground(new java.awt.Color(204, 204, 204));
        Students.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Stud_table.setAutoCreateRowSorter(true);
        Stud_table.setBackground(new java.awt.Color(204, 204, 204));
        Stud_table.setForeground(new java.awt.Color(0, 0, 0));
        Stud_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Stud_table);

        Students.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 700, -1));

        class_list.setBackground(new java.awt.Color(242, 242, 242));
        class_list.setForeground(new java.awt.Color(0, 0, 0));
        class_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Class", "Class 8", "Class 9", "Class 10", " " }));
        class_list.setBorder(null);
        class_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_listActionPerformed(evt);
            }
        });
        Students.add(class_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 180, -1));

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Class :");
        Students.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 92, -1, -1));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Search :");
        Students.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 92, -1, -1));

        Grid_search.setBackground(new java.awt.Color(221, 221, 221));
        Grid_search.setBorder(null);
        Grid_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grid_searchActionPerformed(evt);
            }
        });
        Grid_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Grid_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Grid_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Grid_searchKeyTyped(evt);
            }
        });
        Students.add(Grid_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 94, 170, -1));

        jPanel4.setBackground(new java.awt.Color(240, 84, 84));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/identification_documents_40px.png"))); // NOI18N
        jLabel19.setText("Student List");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 4, -1, -1));

        Students.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        jLabel20.setText("___________________________________");
        Students.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));
        Students.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 680, 110));

        jButton5.setBackground(new java.awt.Color(19, 170, 82));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Create");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Students.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("Edit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Students.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        Delete_B.setBackground(new java.awt.Color(51, 51, 51));
        Delete_B.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Delete_B.setText("Delete");
        Students.add(Delete_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Tools :");
        Students.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 53, -1, -1));

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setText("Refresh Table");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Students.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 110, -1));

        Main_panel.add(Students, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        Home.setMinimumSize(new java.awt.Dimension(900, 500));
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(65, 65, 65));
        kGradientPanel2.setkGradientFocus(100);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kGradientPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, 180));

        Time.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        kGradientPanel2.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Hello,");
        kGradientPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Home.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        Main_panel.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        Fees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Main_panel.add(Fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        getContentPane().add(Main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, 550));

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Home_optMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_optMouseEntered
        
    }//GEN-LAST:event_Home_optMouseEntered
    private void Grid_searchKeyTyped(java.awt.event.KeyEvent evt) { 
        Grid_search.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                search(Grid_search.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                search(Grid_search.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                search(Grid_search.getText());
            }
        });
    }
    public void search(String str){
        dm = (DefaultTableModel) Stud_table.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(dm);
        if(str.length()==0){
            sorter.setRowFilter(null);
        }else{
            sorter.setRowFilter(RowFilter.regexFilter(str));
        }
    }
    private void Student_optMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_optMouseClicked
        Student_opt.setBackground(new java.awt.Color(66, 66, 66));
        Home_opt.setBackground(new java.awt.Color(33,33,33));
        Fees_opt.setBackground(new java.awt.Color(33,33,33));
        ID_opt.setBackground(new java.awt.Color(33,33,33));
            //Panels Visiblity
                Students.setVisible(true);
                Fees.setVisible(false);
                ID.setVisible(false);
                Home.setVisible(false);
    }//GEN-LAST:event_Student_optMouseClicked

    private void ID_optKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ID_optKeyPressed
      
    }//GEN-LAST:event_ID_optKeyPressed

    private void ID_optMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ID_optMouseClicked
        ID_opt.setBackground(new java.awt.Color(66, 66, 66));
        Home_opt.setBackground(new java.awt.Color(33,33,33));
        Student_opt.setBackground(new java.awt.Color(33,33,33));
        Fees_opt.setBackground(new java.awt.Color(33,33,33));
           //Panels Visiblity
            Students.setVisible(false);
            ID.setVisible(true);
            Home.setVisible(false);
            Fees.setVisible(false);
    }//GEN-LAST:event_ID_optMouseClicked

    private void Home_optMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_optMouseClicked
        Home_opt.setBackground(new java.awt.Color(66, 66, 66));
        Fees_opt.setBackground(new java.awt.Color(33,33,33));
        Student_opt.setBackground(new java.awt.Color(33,33,33));
        ID_opt.setBackground(new java.awt.Color(33,33,33));
        //Panels Visiblity
            Students.setVisible(false);
            Fees.setVisible(false);
            ID.setVisible(false);
            Home.setVisible(true);
    }//GEN-LAST:event_Home_optMouseClicked

    private void Logout_optMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_optMouseClicked
       int input = JOptionPane.showConfirmDialog(null, "Do you want to logout", "Logout?", WIDTH, HEIGHT);
       if(input==0){
           this.dispose();
        new Login_Page().setVisible(true);
       }
    }//GEN-LAST:event_Logout_optMouseClicked

    private void Fees_optMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fees_optMouseClicked
        Fees_opt.setBackground(new java.awt.Color(66, 66, 66));
        Home_opt.setBackground(new java.awt.Color(33,33,33));
        Student_opt.setBackground(new java.awt.Color(33,33,33));
        ID_opt.setBackground(new java.awt.Color(33,33,33));
        //Panels Visiblity
            Students.setVisible(false);
            Fees.setVisible(true);
            ID.setVisible(false);
            Home.setVisible(false);
    }//GEN-LAST:event_Fees_optMouseClicked

    private void Fees_optKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fees_optKeyPressed
    }//GEN-LAST:event_Fees_optKeyPressed

    private void class_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_listActionPerformed
            String value = class_list.getSelectedItem().toString();
          System.out.println(value);
          if("Class 9".equals(value)){
             try(Connection con = DriverManager.getConnection(DB_URL,User,Pass)){
                    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select * from class_8";
                    ResultSet rs = st.executeQuery(sql);
                    Stud_table.setModel(DbUtils.resultSetToTableModel(rs));
                   con.close();
              }catch(Exception e){
                  JOptionPane.showMessageDialog(null,"Couldn't retrieve the data! Check the connection and try again!","Error",JOptionPane.ERROR_MESSAGE);
              }
          }
          else if("Class 9".equals(value)){
              try(Connection con = DriverManager.getConnection(DB_URL,User,Pass)){
                    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select * from class_9";
                    ResultSet rs = st.executeQuery(sql);
                    Stud_table.setModel(DbUtils.resultSetToTableModel(rs));
                   con.close();
              }catch(Exception e){
                  JOptionPane.showMessageDialog(null,"Couldn't retrieve the data! Check the connection and try again!","Error",JOptionPane.ERROR_MESSAGE);
              }
          }else if("Class 10".equals(value)){
              try(Connection con = DriverManager.getConnection(DB_URL,User,Pass)){
                    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select * from class_10";
                    ResultSet rs = st.executeQuery(sql);
                    Stud_table.setModel(DbUtils.resultSetToTableModel(rs));
                    con.close();
              }catch(Exception e){
                  JOptionPane.showMessageDialog(null,"Couldn't retrieve the data! Check the connection and try again!","Error",JOptionPane.ERROR_MESSAGE);
              }
          }
    }//GEN-LAST:event_class_listActionPerformed

    private void Grid_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grid_searchActionPerformed

    }//GEN-LAST:event_Grid_searchActionPerformed

    private void Grid_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Grid_searchKeyPressed

    }//GEN-LAST:event_Grid_searchKeyPressed

    private void Grid_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Grid_searchKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Grid_searchKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         String value = class_list.getSelectedItem().toString();
          System.out.println(value);
          if("Class 8".equals(value)){
             try(Connection con = DriverManager.getConnection(DB_URL,User,Pass)){
                    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select * from class_8";
                    ResultSet rs = st.executeQuery(sql);
                    Stud_table.setModel(DbUtils.resultSetToTableModel(rs));
                   con.close();
              }catch(Exception e){
                  e.printStackTrace();
              }
          }
          else if("Class 9".equals(value)){
              try(Connection con = DriverManager.getConnection(DB_URL,User,Pass)){
                    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select * from class_9";
                    ResultSet rs = st.executeQuery(sql);
                    Stud_table.setModel(DbUtils.resultSetToTableModel(rs));
                   con.close();
              }catch(Exception e){
                  e.printStackTrace();
              }
          }else if("Class 10".equals(value)){
              try(Connection con = DriverManager.getConnection(DB_URL,User,Pass)){
                    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select * from class_10";
                    ResultSet rs = st.executeQuery(sql);
                    Stud_table.setModel(DbUtils.resultSetToTableModel(rs));
                    con.close();
              }catch(Exception e){
                  e.printStackTrace();
              }
          }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        new Student_Form().setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassActionPerformed
       String value1 = Class.getSelectedItem().toString();
       if(value1.equals("Class 8")){
           try(Connection con = DriverManager.getConnection(DB_URL,User,Pass)){
               Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select Name from class_8";
                    ResultSet rs = st.executeQuery(sql);
                    while(rs.next()){
                    String name2 = rs.getString("Name");
                    Student.addItem(name2);
                    }
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"Couldn't retrieve the data! Check the connection and try again!","Error",JOptionPane.ERROR_MESSAGE);
           } 
       }
       if(value1.equals("Class 9")){
           try(Connection con = DriverManager.getConnection(DB_URL,User,Pass)){
               Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select Name from class_9";
                    ResultSet rs = st.executeQuery(sql);
                    while(rs.next()){
                    String name2 = rs.getString("Name");
                    Student.addItem(name2);
                    }
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"Couldn't retrieve the data! Check the connection and try again!","Error",JOptionPane.ERROR_MESSAGE);
           }           
       }
       if(value1.equals("Class 10")){
       try(Connection con = DriverManager.getConnection(DB_URL,User,Pass)){
               Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select Name from class_10";
                    ResultSet rs = st.executeQuery(sql);
                    while(rs.next()){
                    String name2 = rs.getString("Name");
                    Student.addItem(name2);
                    }
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"Couldn't retrieve the data! Check the connection and try again!","Error",JOptionPane.ERROR_MESSAGE);
           } }
    }//GEN-LAST:event_ClassActionPerformed

    private void StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentActionPerformed
        String Value2 = Student.getSelectedItem().toString();
        String value1 = Class.getSelectedItem().toString();
        try(Connection con = DriverManager.getConnection(DB_URL,User,Pass)){
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            if(value1.equals("Class 8")){
                ps = con.prepareStatement("select Dob,Phone,BloodGroup from class_8 where Name=?");
                ps.setString(1, Value2);
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    Name1.setText(Value2);
                    Class1.setText(value1);
                    Birthdate1.setText(rs.getString("Dob"));
                    Phone1.setText(rs.getString("Phone"));
                    Blood1.setText(rs.getString("BloodGroup"));
            }
            }
            if(value1.equals("Class 9")){
                ps = con.prepareStatement("select Dob,Phone,BloodGroup from class_9 where Name=?");
                ps.setString(1, Value2);
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    Name1.setText(Value2);
                    Class1.setText(value1);
                    Birthdate1.setText(rs.getString("Dob"));
                    Phone1.setText(rs.getString("Phone"));
                    Blood1.setText(rs.getString("BloodGroup"));
                }
            }
            if(value1.equals("Class 10")){
                ps = con.prepareStatement("select Dob,Phone,BloodGroup from class_10 where Name=?");
                ps.setString(1, Value2);
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    Name1.setText(Value2);
                    Class1.setText(value1);
                    Birthdate1.setText(rs.getString("Dob"));
                    Phone1.setText(rs.getString("Phone"));
                    Blood1.setText(rs.getString("BloodGroup"));
                }
            }
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Couldn't retrieve the data! Check the connection and try again!","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_StudentActionPerformed

    private void ChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseActionPerformed
       JFileChooser FChooser = new JFileChooser();
       FChooser.showOpenDialog(null);
       File f = FChooser.getSelectedFile();
       File_Name = f.getAbsolutePath();
       try{
        File image = new File(File_Name);
           FileInputStream fis = new FileInputStream(image);
           ByteArrayOutputStream baos = new ByteArrayOutputStream();
           byte[] buf = new byte[1024];
           for(int readnum; (readnum=fis.read(buf)) !=-1;)
            {            
                baos.write(buf,0,readnum);                
            }
           P_Image = baos.toByteArray();
           Profile_Image.setIcon(resizeImage(File_Name, buf));
       }catch(IOException e){
           JOptionPane.showMessageDialog(null,"Cannot Open the file","Error",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_ChooseActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        try {
            Toolkit tkp = IdentityCard.getToolkit();
            PrintJob Print_ID = tkp.getPrintJob(this, null, null);
            Graphics G = Print_ID.getGraphics();
            IdentityCard.print(G);
            Print_ID.end();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Cannot print the Identity Card","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_PrintActionPerformed
      
    private ImageIcon resizeImage(String imagePath, byte[] pic) {
        ImageIcon Image_P = null;
        if(imagePath !=null)
        {
            Image_P = new ImageIcon(imagePath);
        
        }else{
            Image_P = new ImageIcon(pic);
        }
                
        Image img = Image_P.getImage();
        Image img2=img.getScaledInstance(Profile_Image.getHeight(), Profile_Image.getWidth(),  Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Window().setVisible(true);
            }
        });
       
       
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Birthdate1;
    private javax.swing.JLabel Blood1;
    private javax.swing.JButton Choose;
    private javax.swing.JComboBox<String> Class;
    private javax.swing.JLabel Class1;
    private javax.swing.JButton Delete_B;
    private javax.swing.JPanel Fees;
    private javax.swing.JPanel Fees_opt;
    private javax.swing.JTextField Grid_search;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Home_opt;
    private javax.swing.JPanel ID;
    private javax.swing.JLabel IDImage;
    private javax.swing.JPanel ID_opt;
    private javax.swing.JPanel IdentityCard;
    private javax.swing.JPanel Logout_opt;
    private javax.swing.JPanel Main_panel;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Phone1;
    private javax.swing.JButton Print;
    private javax.swing.JLabel Profile_Image;
    private javax.swing.JPanel SideBar;
    private javax.swing.JTable Stud_table;
    private javax.swing.JComboBox<String> Student;
    private javax.swing.JPanel Student_opt;
    private javax.swing.JPanel Students;
    private javax.swing.JLabel Time;
    private javax.swing.JComboBox<String> class_list;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables


}