package Source;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tanuj
 */
public class Window extends javax.swing.JFrame {

              static final String DB_URL = "jdbc:mysql://localhost:3306/student"; //Database URL
        static final String User = "root"; //Database Username
        static final String Pass = "";  //Database Password

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBar = new javax.swing.JPanel();
        Logout_opt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Home_opt = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Student_opt = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Attendance_opt = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Main_panel = new javax.swing.JPanel();
        Students = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Stud_table = new javax.swing.JTable();
        class_list = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Grid_search = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Home = new javax.swing.JLayeredPane();
        Attendance = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(900, 550));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(902, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(902, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideBar.setBackground(new java.awt.Color(48, 71, 94));
        SideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout_opt.setBackground(new java.awt.Color(48, 71, 94));
        Logout_opt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout_opt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/Logout_35px.png"))); // NOI18N
        Logout_opt.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, 40, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logout");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logout_opt.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 12, -1, -1));

        SideBar.add(Logout_opt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 50));

        Home_opt.setBackground(new java.awt.Color(48, 71, 94));
        Home_opt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home_opt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_optMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Home_optMouseEntered(evt);
            }
        });
        Home_opt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/home_50px.png"))); // NOI18N
        Home_opt.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, 40, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Home");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home_opt.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 12, -1, -1));

        SideBar.add(Home_opt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 50));

        Student_opt.setBackground(new java.awt.Color(48, 71, 94));
        Student_opt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Student_opt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Student_optMouseClicked(evt);
            }
        });
        Student_opt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/identification_documents_40px.png"))); // NOI18N
        Student_opt.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, 40, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Students");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Student_opt.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 12, -1, -1));
        jLabel6.getAccessibleContext().setAccessibleName("75");

        SideBar.add(Student_opt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 50));

        Attendance_opt.setBackground(new java.awt.Color(48, 71, 94));
        Attendance_opt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Attendance_opt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Attendance_optMouseClicked(evt);
            }
        });
        Attendance_opt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Attendance_optKeyPressed(evt);
            }
        });
        Attendance_opt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/planner_40px.png"))); // NOI18N
        Attendance_opt.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, 40, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Attendance");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Attendance_opt.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 12, -1, -1));

        SideBar.add(Attendance_opt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 50));

        getContentPane().add(SideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        Main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Students.setBackground(new java.awt.Color(221, 221, 221));
        Students.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Stud_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Stud_table);

        Students.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 700, -1));

        class_list.setBackground(new java.awt.Color(242, 242, 242));
        class_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Class", "Class 1", "Class 2", "Class 3", "Class 4" }));
        class_list.setBorder(null);
        class_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_listActionPerformed(evt);
            }
        });
        Students.add(class_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 180, -1));

        jLabel9.setText("Class :");
        Students.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 92, -1, -1));

        jLabel10.setText("Search :");
        Students.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 92, -1, -1));

        Grid_search.setBackground(new java.awt.Color(221, 221, 221));
        Grid_search.setBorder(null);
        Grid_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Grid_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Grid_searchKeyReleased(evt);
            }
        });
        Students.add(Grid_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 94, 170, -1));

        jPanel2.setBackground(new java.awt.Color(240, 84, 84));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Icons/identification_documents_40px.png"))); // NOI18N
        jLabel11.setText("Student List");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 4, -1, -1));

        Students.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        jLabel12.setText("___________________________________");
        Students.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        Main_panel.add(Students, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Main_panel.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        Main_panel.add(Attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(Main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, 550));

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Home_optMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_optMouseEntered
        
    }//GEN-LAST:event_Home_optMouseEntered

    private void Grid_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Grid_searchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Grid_searchKeyPressed

    private void Grid_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Grid_searchKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Grid_searchKeyReleased

    private void Student_optMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_optMouseClicked
            Student_opt.setBackground(Color.decode("222831"));
            Students.setVisible(true);
            Attendance.setVisible(false);
            Home.setVisible(false);
            Home_opt.setBackground(new java.awt.Color(48, 71, 94));
            Attendance_opt.setBackground(new java.awt.Color(48, 71, 94));
    }//GEN-LAST:event_Student_optMouseClicked

    private void Attendance_optKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Attendance_optKeyPressed
      
    }//GEN-LAST:event_Attendance_optKeyPressed

    private void Attendance_optMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Attendance_optMouseClicked
         Attendance_opt.setBackground(Color.decode("222831"));
         Student_opt.setBackground(new java.awt.Color(48, 71, 94));
         Home_opt.setBackground(new java.awt.Color(48, 71, 94));
            Students.setVisible(false);
            Attendance.setVisible(true);
            Home.setVisible(false);
         
    }//GEN-LAST:event_Attendance_optMouseClicked

    private void Home_optMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_optMouseClicked
        Home_opt.setBackground(Color.decode("222831"));
            Students.setVisible(false);
            Attendance.setVisible(false);
            Home.setVisible(true);
        Student_opt.setBackground(new java.awt.Color(48, 71, 94));
        Attendance_opt.setBackground(new java.awt.Color(48, 71, 94));
    }//GEN-LAST:event_Home_optMouseClicked

    private void class_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_listActionPerformed

          
          
          String value = class_list.getSelectedItem().toString();
          System.out.println(value);
          if("Class 1".equals(value)){
             try{
                  
                    Connection con = DriverManager.getConnection(DB_URL,User,Pass);
                    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select * from class_1";
                    ResultSet rs = st.executeQuery(sql);
                    Stud_table.setModel(DbUtils.resultSetToTableModel(rs));
                   con.close();
              }catch(Exception e){
                  e.printStackTrace();
              }
          }
          else if("Class 2".equals(value)){
              try{
                 
                    Connection con = DriverManager.getConnection(DB_URL,User,Pass);
                    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select * from class_2";
                    ResultSet rs = st.executeQuery(sql);
                    Stud_table.setModel(DbUtils.resultSetToTableModel(rs));
                   con.close();
              }catch(Exception e){
                  e.printStackTrace();
              }
          }else if("Class 3".equals(value)){
              try{
                  
                    Connection con = DriverManager.getConnection(DB_URL,User,Pass);
                    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select * from class_3";
                    ResultSet rs = st.executeQuery(sql);
                    Stud_table.setModel(DbUtils.resultSetToTableModel(rs));
                    Stud_table.
                    con.close();
              }catch(Exception e){
                  e.printStackTrace();
              }
          }else if("Class 4".equals(value)){
              try{
                 
                    Connection con = DriverManager.getConnection(DB_URL,User,Pass);
                    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    String sql = "select * from class_4";
                    ResultSet rs = st.executeQuery(sql);
                    Stud_table.setModel(DbUtils.resultSetToTableModel(rs));
                   con.close();
              }catch(Exception e){
                  e.printStackTrace();
              }
          }
      
    }//GEN-LAST:event_class_listActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Window().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Attendance;
    private javax.swing.JPanel Attendance_opt;
    private javax.swing.JTextField Grid_search;
    private javax.swing.JLayeredPane Home;
    private javax.swing.JPanel Home_opt;
    private javax.swing.JPanel Logout_opt;
    private javax.swing.JPanel Main_panel;
    private javax.swing.JPanel SideBar;
    private javax.swing.JTable Stud_table;
    private javax.swing.JPanel Student_opt;
    private javax.swing.JLayeredPane Students;
    private javax.swing.JComboBox<String> class_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
